### ISSUE TITLE
Three undefined names

### ISSUE THREAD

**Issue by cclauss** [msracver/Flow-Guided-Feature-Aggregation#1]
flake8 testing of https://github.com/msracver/Flow-Guided-Feature-Aggregation on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/bbox/setup_linux.py:46:48: F821 undefined name 'CUDA'
            self.set_executable('compiler_so', CUDA['nvcc'])
                                               ^

./lib/nms/seq_nms.py:50:26: F821 undefined name 'areas2'
                areas1 = areas2
                         ^

./lib/rpn/rpn.py:72:39: F821 undefined name 'get_pair_image'
    imgs, ref_imgs, eq_flags, roidb = get_pair_image(roidb, cfg)
                                      ^
```

**Comment by einsiedler0408** [comment]
Thanks for this! And these undefined names will not affect results.

1. F821 undefined name 'CUDA':  because 'bbox' does not have 'cu' files, this line does not work
2. F821 undefined name 'areas2':  working as designed
3. F821 undefined name 'get_pair_image': just fixed and this function will not be used by FGFA, but still thx!
